# Site Settings
title: 'InSource Software'
slogan: 'Our Engineers &middot; Your Source'
description: 'We use customer driven development, which allows us to deliver tailored solutions to real world problems through shared vision built on trust, teamwork and collaboration. Innovation and craftsmanship come standard.'
meta: 'Experts specializing in Big Data, Search & Microservices in Java & JavaScript using Spring Boot, Elasticsearch, Hadoop, & ZeroMQ.'
language: 'en'
url: 'https://insource.io'
baseurl: ''
logo: 'logo.png'
logo2: 'logo2.png'
author: Steve
email: contact@insource.io
phone: '+1 (402) 909-1695'
address: 'Papillion, NE 68046'

# Social Media
github_username:  InSourceSoftware
facebook_username: InSourceSoftware
twitter_username: InSourceOmaha

# Jekyll Settings
collections:
#  articles:
#    output: true
#    permalink: /:collection/:title:output_ext
  posts:
    output: true
    permalink: /blog/:categories/:title:output_ext
sass:
  sass_dir: _sass
  style: :compressed
plugins:
- jekyll-gist
- jekyll-paginate
paginate: 5                      # Paginates all X entries
paginate_path: '/blog/page-:num'   # Pagination path › Important for blog page in /blog/ to work
markdown: kramdown
permalink: /:categories/:title/
highlight: rouge
excerpt_separator: '<!--more-->'
include:
- '.htaccess'
exclude:
- .sass-cache
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
- INSTALL.md

# Used › default.html front-matter and compress.html
compress_html:
  clippings: all
  comments: ['<!-- ', ' -->']
  endings: all
  profile: false
  ignore:
    envs: [development]

# Default Settings
defaults:
  -
    scope:
      path: '' 				# an empty string here means all files in the project
      type: 'pages'
    values:
      show_meta: false 	# Hide metadata for all pages
      sidebar: none
      comments: false
      author: Steve     # Default author for pages
  -
    scope:
      path: ''
      type: 'posts'
    values:
      show_meta: true   # Show metadata for all posts
      sidebar: none
      comments: false
      reCaptcha: true
      author: Steve     # Default author for posts
  -
    scope:
      path: ''
      type: 'articles'
    values:
      show_meta: true   # Show metadata for all posts
      sidebar: none
      comments: true
      reCaptcha: true
      author: Steve     # Default author for posts

# SEO settings
google_author:             'https://plus.google.com/u/0/b/116388734123404805483/116388734123404805483'
#google_site_verification:  'Vk0IOJ2jwG_qEoG7fuEXYqv0m2rLa8P778Fi_GrsgEQ'
#bing_webmastertools_id:    '0FB4C028ABCF07C908C54386ABD2D97F'

# Favicons
favicon-32x32:                          'favicon-32x32.png'
touch-icon-192x192:                     'touch-icon-192x192.png'
apple-touch-icon-180x180-precomposed:   'apple-touch-icon-180x180-precomposed.png'
apple-touch-icon-152x152-precomposed:   'apple-touch-icon-152x152-precomposed.png'
apple-touch-icon-144x144-precomposed:   'apple-touch-icon-144x144-precomposed.png'
apple-touch-icon-120x120-precomposed:   'apple-touch-icon-120x120-precomposed.png'
apple-touch-icon-114x114-precomposed:   'apple-touch-icon-114x114-precomposed.png'
apple-touch-icon-76x76-precomposed:     'apple-touch-icon-76x76-precomposed.png'
apple-touch-icon-72x72-precomposed:     'apple-touch-icon-72x72-precomposed.png'
apple-touch-icon-precomposed:           'apple-touch-icon-precomposed.png'
msapplication_tileimage:                'msapplication_tileimage.png'               # Size 144x144
msapplication_tilecolor:                '#fabb00'

# Google Analytics
google_analytics_tracking_id: UA-77117959-1

# reCaptcha
reCaptcha:
  siteKey: "6LddKsMUAAAAAPrjH-LQTgI2u0OPcV5lQk8_WDLw"
  secret: "cSqvj2KCCdIuNbnG/pXyh6oG2DWKom4gjeNWTtvZFzHCTqibVIqhHMXVEO01o7sD6N96aqAmkqLpPtFLMRkNdhyQdnzjxFtRBhNKDbe0T35qMgE5MWEsDreBqSyxKoInk4EqSVYTpPy2hMDQKRkTkHbIyMyPZcDJ98xv6Pm8oc/VqrZpbt1w0Sv4YN1FrAwCpLCU3qE7M9rn/fO7m9lH5TYpjZtEBzX5Xp4aPx0bnF/qODpWfQE/tfA7JY2JtXMzQKGlZY/Ec5j0Obufbwi+e5nfiezImJqcfSrvskIC7AF0UIHRloY1fuk5XbodvAwxoMvQc0EVPjN8RvmIk3Xt7zCD1Tqysd2RwQdotnwTrd1T/ZxUx7UYWa5H5Q2QUK6qLac9ZiJo/2JVNJdJ1Tm9zMvtbqXP0rKb0nl24avYHm3/1S80mcHMA1eihfI5bsgnyOS4LDLHWZUffcx+1KijaKqZ/9en4B67LgEpIxZlcfxzlLYims8QasrVVNk6ynMoBDCRD24/T4wT9NYTGEHLAfk0/F55E8kxBW0FmG2fwmKtv8rlQ+SSTkhGx574qG0k8RMfe2yg24lOc9fntNDv/jGe7YXqHaIZ7mz/8Nywv70k/nCNlfOxx987r79fm9c82pLGk8Wcp3b3dSBEnqV/ex90SRxpR+EwNLq4sGKVGnM="

# Google App Scripts
google:
  scripts:
    url: "https://script.google.com/macros/s/AKfycbxeWuqOhQDk39-lqzSjTO47p2v3kVa3BgYHTN4gf1SLMIf3mrSK/exec"
    challenge: 31

# Prose Editor
prose:
  rooturl: "_posts"
  siteurl: "http://insource.io"
  media: "images/stock"
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "post"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          help: "Title of the post."
          placeholder: "Weekly Update, July 26th"
      - name: "subheadline"
        field:
          element: "text"
          label: "Subheadline"
          help: "Appears below the title of the post."
          placeholder: "Weekly Update Series"
      - name: teaser
        field:
          element: "text"
          label: "Teaser"
          help: "Brief introduction to the post, seen below the subheadline on index pages."
          placeholder: "This week in the news, we learned..."
      - name: "categories"
        field:
          element: "select"
          label: "Category"
          help: "Category of the post."
          options:
            - name: "Post"
              value: "post"
            - name: "Article"
              value: "article"
      - name: "image/title"
        field:
          element: "text"
          label: "Post image"
          help: "Image is relative to /images/"
          placeholder: "stock/code-1920.jpg"
      - name: "image/thumb"
        field:
          element: "text"
          label: "Post thumbnail"
          help: "Image is relative to /images/"
          placeholder: "stock/code-1920-t.jpg"
